<?php

return [
    'about' => [
        'route' => 'about',
        'menu_label' => "L'association",
        'eyebrow' => "L'association",
        'title' => 'Qui sommes-nous ?',
        'description' => 'La Quinzaine Obstetricale est une association engagee dans la promotion de la sante des femmes, de la perinatalite et de la formation des professionnels de sante en Guyane.',
        'hero_image_path' => 'images/page-headers/quinzaine-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => true,
    ],
    'actions' => [
        'route' => 'actions',
        'menu_label' => 'Nos actions',
        'eyebrow' => 'Nos actions',
        'title' => 'Des projets concrets pour informer, former, innover et agir',
        'description' => 'Chaque action repond a un besoin du territoire : prevention, formation, dialogue public, ressources professionnelles et innovation en sante.',
        'hero_image_path' => 'images/page-headers/guyane-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => true,
    ],
    'public' => [
        'route' => 'public',
        'menu_label' => 'Sante des femmes',
        'eyebrow' => 'Sante des femmes',
        'title' => 'Des fiches simples classees par theme',
        'description' => 'Des reperes accessibles pour comprendre les grandes etapes de la vie, identifier les sujets a discuter avec un professionnel et trouver les bons relais.',
        'hero_image_path' => 'images/page-headers/quinzaine-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => true,
    ],
    'news' => [
        'route' => 'news',
        'menu_label' => 'Actualites',
        'eyebrow' => 'Actualites',
        'title' => 'Articles, tribunes, interviews et publications',
        'description' => "Un espace pour suivre les prises de parole, les communiques, les publications scientifiques et les nouvelles ressources de l'association.",
        'hero_image_path' => 'images/page-headers/guyane-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => true,
    ],
    'agenda' => [
        'route' => 'agenda',
        'menu_label' => 'Agenda',
        'eyebrow' => 'Agenda',
        'title' => 'Les rendez-vous de la Quinzaine',
        'description' => "Toutes les manifestations avec inscription en ligne : conferences, ateliers, rencontres professionnelles et temps d'echange ouverts au public.",
        'hero_image_path' => 'images/page-headers/quinzaine-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => true,
    ],
    'research' => [
        'route' => 'research',
        'menu_label' => 'Recherche',
        'eyebrow' => 'Recherche et innovation',
        'title' => 'Developper les connaissances et les solutions utiles au territoire',
        'description' => 'Recherche, coordination et experimentation pour faire progresser les pratiques en sante des femmes et perinatalite.',
        'hero_image_path' => 'images/page-headers/guyane-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => true,
    ],
    'contact' => [
        'route' => 'contact',
        'menu_label' => 'Contact',
        'eyebrow' => 'Contact',
        'title' => "Entrer en contact avec l'association",
        'description' => 'Une question, une proposition, un partenariat ou une demande de ressource : contactez notre equipe.',
        'hero_image_path' => 'images/page-headers/quinzaine-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => true,
    ],
    'join' => [
        'route' => 'join',
        'menu_label' => 'Nous soutenir',
        'eyebrow' => 'Nous soutenir',
        'title' => 'Rejoindre et soutenir La Quinzaine Obstetricale',
        'description' => 'Adherer, donner ou participer permet de soutenir les actions de terrain, la prevention et la formation.',
        'hero_image_path' => 'images/page-headers/guyane-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => false,
    ],
    'pro' => [
        'route' => 'pro',
        'menu_label' => 'Espace pro',
        'eyebrow' => 'Espace professionnels',
        'title' => 'Ressources, coordination et formation continue',
        'description' => 'Un espace pour les professionnels impliques dans le parcours perinatal et la sante des femmes.',
        'hero_image_path' => 'images/page-headers/quinzaine-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => false,
    ],
];
