<?php

return [
    'about' => [
        'route' => 'about',
        'menu_label' => "L'association",
        'eyebrow' => "L'association",
        'title' => 'Qui sommes-nous ?',
        'description' => 'La Quinzaine Obstétricale est une association engagée dans la promotion de la santé de la femme, de la périnatalité et de la formation des professionnels de santé en Guyane.',
        'hero_image_path' => 'images/page-headers/quinzaine-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => true,
    ],
    'actions' => [
        'route' => 'actions',
        'menu_label' => 'Nos actions',
        'eyebrow' => 'Nos actions',
        'title' => 'Des projets concrets pour informer, former, innover et agir',
        'description' => 'Chaque action répond à un besoin du territoire : prévention, formation, dialogue public, ressources professionnelles et innovation en santé.',
        'hero_image_path' => 'images/page-headers/guyane-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => false,
    ],
    'public' => [
        'route' => 'public',
        'menu_label' => 'Santé de la femme',
        'eyebrow' => 'Santé de la femme',
        'title' => 'Des fiches simples classées par thème',
        'description' => 'Des repères accessibles pour comprendre les grandes étapes de la vie, identifier les sujets à discuter avec un professionnel et trouver les bons relais.',
        'hero_image_path' => 'images/page-headers/quinzaine-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => true,
    ],
    'news' => [
        'route' => 'news',
        'menu_label' => 'Actualités',
        'eyebrow' => 'Actualités',
        'title' => 'Articles, tribunes, interviews et publications',
        'description' => "Un espace pour suivre les prises de parole, les communiqués, les publications scientifiques et les nouvelles ressources de l'association.",
        'hero_image_path' => 'images/page-headers/guyane-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => true,
    ],
    'agenda' => [
        'route' => 'agenda',
        'menu_label' => 'Agenda',
        'eyebrow' => 'Agenda',
        'title' => 'Les rendez-vous de la Quinzaine',
        'description' => "Toutes les manifestations avec inscription en ligne : conférences, ateliers, rencontres professionnelles et temps d'échange ouverts au public.",
        'hero_image_path' => 'images/page-headers/quinzaine-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => true,
    ],
    'research' => [
        'route' => 'research',
        'menu_label' => 'Recherche',
        'eyebrow' => 'Recherche et innovation',
        'title' => 'Développer les connaissances et les solutions utiles au territoire',
        'description' => 'Recherche, coordination et expérimentation pour faire progresser les pratiques en santé de la femme et périnatalité.',
        'hero_image_path' => 'images/page-headers/guyane-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => false,
    ],
    'contact' => [
        'route' => 'contact',
        'menu_label' => 'Contact',
        'eyebrow' => 'Contact',
        'title' => "Entrer en contact avec l'association",
        'description' => 'Une question, une proposition, un partenariat ou une demande de ressource : contactez notre équipe.',
        'hero_image_path' => 'images/page-headers/quinzaine-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => true,
    ],
    'join' => [
        'route' => 'join',
        'menu_label' => 'Nous soutenir',
        'eyebrow' => 'Nous soutenir',
        'title' => 'Rejoindre et soutenir La Quinzaine Obstétricale',
        'description' => 'Adhérer, donner ou participer permet de soutenir les actions de terrain, la prévention et la formation.',
        'hero_image_path' => 'images/page-headers/guyane-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => false,
    ],
    'pro' => [
        'route' => 'pro',
        'menu_label' => 'Espace pro',
        'eyebrow' => 'Espace professionnel',
        'title' => 'Ressources, coordination et formation continue',
        'description' => 'Un espace pour les professionnels impliqués dans le parcours périnatal et la santé de la femme.',
        'hero_image_path' => 'images/page-headers/quinzaine-page-example.png',
        'title_size' => 'normal',
        'show_in_menu' => false,
    ],
];
